services:
  organizerservice:
    image: orbitalteapot/openaudiblebookorganizerservice
    build:
      context: .
      dockerfile: BookOrganizerService/Dockerfile

  organizerconsole:
    image: orbitalteapot/openaudiblebookorganizerconsole
    build:
      context: .
      dockerfile: BookOrganizerConsole/Dockerfile
